version: '3.1'  # Use a suitable version for your needs

services:
  db:
    image: postgres:latest  # Use the version of PostgreSQL you need
    environment:
      POSTGRES_USER: user     # Replace with your desired username
      POSTGRES_PASSWORD: password  # Replace with your desired password
      POSTGRES_DB: ecommerce    # Replace with your desired database name
    ports:
      - "5432:5432"  # Map the container port 5432 to the host
    volumes:
      - my_db_data:/var/lib/postgresql/data  # Persist database data

volumes:
  my_db_data:  # This named volume will store the PostgreSQL database data
